schema_version: 1

context:
  name: dominodatalab
  version: "1.4.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/dominodatalab-${{ version }}.tar.gz
  sha256: 550bbd7c5cb13a6d5ae469f559b5f9436e8f2498e9b3d7a3c56739bebea23efd

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - packaging
    - requests >=2.4.2
    - beautifulsoup4 >=4.11,<5
    - polling2 >=0.5.0,<0.6
    - urllib3 >=1.26.19,<3
    - typing-extensions >=4.13.0,<5
    - frozendict >=2.3
    - python-dateutil >=2.8.2,<3
    - retry ==0.9.2

tests:
  - python:
      imports:
        - domino
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Python bindings for the Domino API
  license: Apache-2.0
  license_file: LICENSE.txt
  homepage: https://github.com/dominodatalab/python-domino

extra:
  recipe-maintainers:
    - janjagusch
